import React,{createContext} from 'react'
import App from './App'


export const Api = createContext();
const Main = () => {

  let BuyDatas=[
       {
          id: 0,
          name:"java",
          about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
          about1:"Java is a platform-independent, object-oriented programming language (OOP). It is not to be confused with JavaScript, a scripting language used to create dynamic web pages.",
          Extend:"The extends keyword extends a class (indicates that a class is inherited from another class).",
          Extend1:"In Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
          Extend2:"Although both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
          img:"https://c4.wallpaperflare.com/wallpaper/274/358/377/angular-code-coding-color-codes-wallpaper-preview.jpg",
          example:"In Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
          example1:". To declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
          example2:"Everything in Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
          variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
          Operator:"A variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
          why:"Java was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
       },
       {
        id:0,
        name:"java",
        about:"Thank you for downloading this release of the Java™ Platform, Standard Edition Development Kit (JDK™). The JDK is a development environment for building applications and components using the Java programming language.",
        about1:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
        Extend:"The extends keyword extends a class (indicates that a class is inherited from another class).In Java, it is possible to inherit attributes and methods from one class to another. We group the ",
        Extend1:"subclass (child) - the class that inherits from another class",
        Extend2:"superclass (parent) - the class being inherited from",
        img:"https://c4.wallpaperflare.com/wallpaper/92/845/277/code-java-programming-life-hd-wallpaper-preview.jpg",
        example:" There are two main keywords, “extends” and “implements” which are used in Java for inheritance. In this article, the difference between extends and implements is discussed.",
        example1:" In Java, the extends keyword is used to indicate that the class which is being defined is derived from the base class using inheritance. So basically, extends keyword is used to extend the functionality of the parent class to the subclass",
        example2:" In Java, multiple inheritances are not allowed due to ambiguity. Therefore, a class can extend only one class to avoid ambiguity.",
        variables:"A variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:" variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"Java was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:1,
        name:"javaScript",
        about:"JavaScript, often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"JavaScript, often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:"The extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"In Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Although both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/129/671/727/code-web-development-javascript-html-programming-hd-wallpaper-preview.jpg",
        example:"In Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:". To declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"Everything in Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"A variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"Java was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:1,
        name:"javaScript",
        about:" often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"JavaScript, often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:"The extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"In Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Although both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/201/905/258/typography-gray-background-javascript-code-wallpaper-preview.jpg",
        example:"In Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"JAVA was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:2,
        name:"PHP",
        about:" PHP is a recursive acronym for PHP: Hypertext Preprocessor",
        about1:" PHP is a server side scripting language that is embedded in HTML. It is used to manage dynamic content, databases, session tracking, even build entire e-commerce sites.",
        Extend:"The extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"In Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Although both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/73/1013/93/code-programming-php-wallpaper-preview.jpg",
        example:"PHP Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:" PHPDeclare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:" PHPIn Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:" PHPDeclaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:" PHPVariable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"PHP was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:2,
        name:"PHP",
        about:" often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/708/590/349/minimalism-pixel-art-vladstudio-php-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"JAVA was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
     
      },
      {
        id:3,
        name:"SQL",
        about:" SQLoften abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:" SQLabbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:"  SQL extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:" SQL Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"SQL the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/456/1007/696/learnmotto-wallpaper-preview.jpg",
        example:" SQL Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:" Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"OF a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"SQL was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
     
      },
      {
        id:3,
        name:"SQL1",
        about:" often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/916/819/593/dark-humor-humor-programming-quote-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"JAVA was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:4,
        name:"C",
        about:"  C often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"C++ the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/646/629/312/code-computer-syntax-highlighting-inception-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"C++ was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:4,
        name:"C++",
        about:" C++ often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" C++extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:" C++Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c1.wallpaperflare.com/preview/793/318/452/source-code-code-programming-c.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"C++ was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:5,
        name:"REACT JS",
        about:" often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" REACTJS  keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"REACTJS  the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c0.wallpaperflare.com/preview/591/474/555/dark-script-jetbrain-webstorm.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"REACTJS  Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"REACTJS  was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:5,
        name:"REACTJS ",
        about:"  REACTJS often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:" REACTJS Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/925/878/321/react-native-reactjs-hd-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"REACTJS  Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"REACTJS  was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:6,
        name:"ANGULAR JS",
        about:" often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/916/819/593/dark-humor-humor-programming-quote-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"ANGULAR JS was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:6,
        name:"ANGULAR JS",
        about:"  ANGULAR JSoften abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"ANGULAR JS it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c1.wallpaperflare.com/preview/552/758/364/computer-laptop-macbook-coding.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"ANGULAR JS a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"ANGULAR JS was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:7,
        name:"VUE JS",
        about:"  VUE JS often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:"VUE JS extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:" VUE JSBoth the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/851/501/292/programming-code-minimalism-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"VUE JS Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"VUE JS Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"VUE JS was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:7,
        name:"VUE JS",
        about:" VUE JSoften abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"VUE JS it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/967/89/86/minimalism-code-quote-text-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"VUE JS Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"VUE JS was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:8,
        name:"BOOTSTRAP",
        about:" BOOTSTRA often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:"abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1:"Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c0.wallpaperflare.com/preview/378/652/5/website-html-form-dark.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:" BOOTSTRAIn Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:"Declaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"BOOTSTRA was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },
      {
        id:8,
        name:"BOOTSTRAP",
        about:" BOOTSTRA often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        about1:" BOOTSTRAabbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries.",
        Extend:" extends keyword extends a class (indicates that a class is inherited from another class).",
        Extend1: "BOOTSTRA Java, it is possible to inherit attributes and methods from one class to another. We group the  into two categories: subclass (child) - the class that inherits from another class.",
        Extend2:"Both the keywords align with the concept of inheritance, the implements keyword is primarily associated with abstraction and used to define a contract, and extends is used to extend a class's existing functionality",
        img:"https://c4.wallpaperflare.com/wallpaper/919/764/983/twitter-bootstrap-wallpaper-preview.jpg",
        example:" Java, there are 51 keywords. Some of the keywords in Java are: abstract, boolean, byte, char, long, short, int, finally, extends, implements, interface, package, new, while, for, do, break, continue, return, public, private, this, case, final, default, etc",
        example1:"Declare a class in Java, use the following format: class ClassName { // class body } Declaring a class in Java. The name of the class should be followed by the keyword class .",
        example2:"In Java is associated with classes and objects, along with its attributes and methods. For example: in real life, a car is an object. The car has attributes, such as weight and color, and methods, such as drive and brake.",
        variables:" BOOTSTRADeclaration of a variable in a computer programming language is a statement used to specify the variable name and its data type. Declaration tells the compiler about the existence of an entity in the program and its location. When you declare a variable, you should also initialize it.",
        Operator:"Variable name can consist of Capital letters A-Z, lowercase letters a-z digits 0-9, and two special characters such as _ underscore and $ dollar sign. The first character must not be a digit. Blank spaces cannot be used in variable names. Java keywords cannot be used as variable names",
        why:"JAVA was designed to be easy to use and is therefore easy to write, compile, debug, and learn than other programming languages. Java is object-oriented. This allows you to create modular programs and reusable code. Java is platform-independent.",
      },    
 

  ]
 

  let singleData =[
        {
          id:0,
          name:"Java",
          Created:"Yatharth shukla",
          Last_updated:"9/2023",
          Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
          img:"https://wallpapercave.com/dwp1x/wp7250032.png",
          about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
          Introduction:"History: Java’s history is very interesting. It is a programming language created in 1991. James Gosling, Mike Sheridan, and Patrick Naughton, a team of Sun engineers known as the Green team initiated the Java language in 1991. Sun Microsystems released its first public implementation in 1996 as Java 1.0. It provides no-cost -run-times on popular platforms. Java1.0 compiler was re-written in Java by Arthur Van Hoff to strictly comply with its specifications. With the arrival of Java 2, new versions had multiple configurations built for different types of platforms.",
          VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
          Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
          Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
          QuestionAnswer:"We are sharing Top 60 Core Java Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
          p_language:"java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible",
        },
        {
            id:1,
            name:"JavaScript",
            Created:"Aman kumar",
            Last_updated:"4/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://c4.wallpaperflare.com/wallpaper/967/71/738/javascript-minimalism-programmers-wallpaper-preview.jpg",
            about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
          Introduction:"History: Java’s history is very interesting. It is a programming language created in 1991. James Gosling, Mike Sheridan, and Patrick Naughton, a team of Sun engineers known as the Green team initiated the Java language in 1991. Sun Microsystems released its first public implementation in 1996 as Java 1.0. It provides no-cost -run-times on popular platforms. Java1.0 compiler was re-written in Java by Arthur Van Hoff to strictly comply with its specifications. With the arrival of Java 2, new versions had multiple configurations built for different types of platforms.",
          VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
          Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
          Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
          QuestionAnswer:"We are sharing Top 60 Core Java Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
        
            p_language:"JavaScript, often abbreviated as JS, is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. As of 2022, 98% of websites use JavaScript on the client side for webpage behavior, often incorporating third-party libraries",
          },
          {
            id:2,
            name:"PHP",
            Created:"Yesh shukla",
            Last_updated:"5/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://images.unsplash.com/photo-1535551951406-a19828b0a76b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8cGhwfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60.jpg",
            about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
            Introduction:"History: Java’s history is very interesting. It is a programming language created in 1991. James Gosling, Mike Sheridan, and Patrick Naughton, a team of Sun engineers known as the Green team initiated the Java language in 1991. Sun Microsystems released its first public implementation in 1996 as Java 1.0. It provides no-cost -run-times on popular platforms. Java1.0 compiler was re-written in Java by Arthur Van Hoff to strictly comply with its specifications. With the arrival of Java 2, new versions had multiple configurations built for different types of platforms.",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Java Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
          
            p_language:"PHP is a general-purpose scripting language geared toward web development. It was originally created by Danish-Canadian programmer Rasmus Lerdorf in 1993 and released in 1995. The PHP reference implementation is now produced by The PHP Group.",
          },
          {
            id:3,
            name:"SQL",
            Created:"Arman sir",
            Last_updated:"4/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://images.unsplash.com/photo-1662027044921-6febc57a0c53?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8U1FMfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60.jpg",
            about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
            Introduction:"History: Java’s history is very interesting. It is a programming language created in 1991. James Gosling, Mike Sheridan, and Patrick Naughton, a team of Sun engineers known as the Green team initiated the Java language in 1991. Sun Microsystems released its first public implementation in 1996 as Java 1.0. It provides no-cost -run-times on popular platforms. Java1.0 compiler was re-written in Java by Arthur Van Hoff to strictly comply with its specifications. With the arrival of Java 2, new versions had multiple configurations built for different types of platforms.",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Java Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
          
            p_language:"Structured Query Language, abbreviated as SQL, is a domain-specific language used in programming and designed for managing data held in a relational database management system, or for stream processing in a relational data stream management system.",
          },
          {
            id:4,
            name:"C-C++",
            Created:"Abhishek sir",
            Last_updated:"3/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://images.unsplash.com/photo-1635775017492-1eb935a082a4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YyUyQiUyQnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60.jpg",
            about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
            Introduction:"History: Java’s history is very interesting. It is a programming language created in 1991. James Gosling, Mike Sheridan, and Patrick Naughton, a team of Sun engineers known as the Green team initiated the Java language in 1991. Sun Microsystems released its first public implementation in 1996 as Java 1.0. It provides no-cost -run-times on popular platforms. Java1.0 compiler was re-written in Java by Arthur Van Hoff to strictly comply with its specifications. With the arrival of Java 2, new versions had multiple configurations built for different types of platforms.",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Java Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
          
            p_language:"C++ is a high-level, general-purpose programming language created by Danish computer scientist Bjarne Stroustrup.",
          },
          {
            id:5,
            name:"React js",
            Created:"Pranjal shukla",
            Last_updated:"7/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://images.unsplash.com/photo-1670057037226-b3d65909424f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHJlYWN0anN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60.jpg",
            about:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
            Introduction:"History: Java’s history is very interesting. It is a programming language created in 1991. James Gosling, Mike Sheridan, and Patrick Naughton, a team of Sun engineers known as the Green team initiated the Java language in 1991. Sun Microsystems released its first public implementation in 1996 as Java 1.0. It provides no-cost -run-times on popular platforms. Java1.0 compiler was re-written in Java by Arthur Van Hoff to strictly comply with its specifications. With the arrival of Java 2, new versions had multiple configurations built for different types of platforms.",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Java Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
          
            p_language:"React is a declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called “components”. React has a few different kinds of components, but we'll start with React.Component subclasses: class ShoppingList extends React.",
          },
          {
            id:6,
            name:"Angular js",
            Created:"Karan sir",
            Last_updated:"9/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://c4.wallpaperflare.com/wallpaper/10/887/781/angular-javascript-html-wallpaper-preview.jpg",
            about:"AngularJS is a discontinued free and open-source JavaScript-based web framework for developing single-page applications. It was maintained mainly by Google and a community of individuals and corporations.",
            Introduction:"AngularJS is a JavaScript framework. It can be added to an HTML page with a <script> tag.AngularJS extends HTML attributes with Directives, and binds data to HTML with Expressions",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Angular js Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
          
            p_language:"AngularJS is a discontinued free and open-source JavaScript-based web framework for developing single-page applications. It was maintained mainly by Google and a community of individuals and corporations.",
          },
          {
            id:7,
            name:"Vue js",
            Created:"Ben sir",
            Last_updated:"1/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://images.unsplash.com/photo-1607799279861-4dd421887fb3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dnVlLmpzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60.jpg",
            about:"Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. It was created by Evan You, and is maintained by him and the rest of the active core team members.",
            Introduction:"Vue (pronounced /vjuː/, like view) is a JavaScript framework for building user interfaces. It builds on top of standard HTML, CSS, and JavaScript and provides a declarative and component-based programming model that helps you efficiently develop user interfaces, be they simple or complex.",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Vuejs Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",
            p_language:"Vue.js is an open-source model viewmodel front end JavaScript framework for building user interfaces and single-page applications. It was created by Evan You, and is maintained by him and the rest of the active core team members",
          },
          {
            id:8,
            name:"Bootstrap",
            Created:"Shiving sir",
            Last_updated:"6/2023",
            Language:["English","Hindi"," Indonesian","Italian","Portuguese","Romanian","Spanish"],
            img:"https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Ym9vdHN0cmFwfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60.jpg",
            about:"Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains HTML, CSS and JavaScript-based design templates for typography, forms, buttons, navigation, and other interface components.",
            Introduction:"What is Bootstrap? Bootstrap is a free, open source front-end development framework for the creation of websites and web apps. Designed to enable responsive development of mobile-first websites, Bootstrap provides a collection of syntax for template designs.",
            VariableAndDataType:"Variable in Java is a data container that stores the data values during Java program execution. Every variable is assigned data type which designates the type and quantity of value it can hold. Variable is a memory location name of the data.",
            Operator:"Operators are special symbols that perform specific operations on one, two, or three operands, and then return a result. As we explore the operators of the Java programming language, it may be helpful for you to know ahead of time which operators have the highest precedence.",
            Function:"A method is a block of code which only runs when it is called. You can pass data, known as parameters, into a method. Methods are used to perform certain actions, and they are also known as functions.",
            QuestionAnswer:"We are sharing Top 60 Core Bootstrap Interview Questions and Answers And Top 20 java interview Programming questions; these questions are frequently asked by the recruiters. Java questions can be asked from any core java topic.",  
            p_language:"Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains HTML, CSS and JavaScript-based design templates for typography, forms, buttons, navigation, and other interface components.",
          },
  ]

  let data = [
        {
         id:0,
         name:"java",
         price: 999,
         amount :1,
         img:"https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8amF2YSUyMGxhbmd1YWdlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
         ittle:"java is a prograniming language and it use for web,App development and it is very secure language "
        },
        {
         id:1,
         name:"javaScript",
         price: 299,
         amount :1,
         img:"https://images.unsplash.com/photo-1527427337751-fdca2f128ce5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8amF2YXNjcmlwdCUyMGNvZGV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
         ittle:"javaScript is a prograniming language and it use for web,App development and it is very secure language "
        },
        {
         id:2,
         name:"PHP",
         price: 399,
         amount :1,
         img:"https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGMlMjBsYW5ndWFnZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
         ittle:"PHP is a prograniming language and it use for web,App development and it is very secure language "
        },
        {
         id:3,
         name:"SQL",
         price: 199,
         amount :1,
         img:"https://images.unsplash.com/photo-1483817101829-339b08e8d83f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8U1FMJTIwY29kZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
         ittle:"SQL is a prograniming language and it use for web,App development and it is very secure language "
        },
        {
         id:4,
         name:"C-C++",
         price: 99,
         amount :1,
         img:"https://images.unsplash.com/photo-1508921108053-9f757ead871c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YyUyQiUyQnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
         ittle:"C/C++ is a prograniming language and it use for web,App development and it is very secure language "
        },
        {
         id:5,
         name:"ReactJs",
         price: 599,
         amount :1,
         img:"https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cmVhY3R8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
         ittle:"React is a prograniming language and it use for web,App development and it is very secure language "
        },
        {
          id:6,
          name:"AngularJs",
          price: 699,
          amount :1,
          img:"https://cdn.pixabay.com/photo/2016/11/19/14/00/code-1839406__340.jpg",
          ittle:"React is a prograniming language and it use for web,App development and it is very secure language "
         }, {
          id:7,
          name:"VueJs",
          price: 399,
          amount :1,
          img:"https://cdn.pixabay.com/photo/2016/11/23/14/45/coding-1853305__340.jpg",
          ittle:"React is a prograniming language and it use for web,App development and it is very secure language "
         }, {
          id:8,
          name:"Bootstrap",
          price: 99,
          amount :1,
          img:"https://cdn.pixabay.com/photo/2014/12/30/05/42/source-code-583537__340.jpg",
          ittle:"React is a prograniming language and it use for web,App development and it is very secure language "
         },
        ];

  return (
     <Api.Provider value={{data, singleData, BuyDatas}}>
         <App/>
     </Api.Provider>
  )
}


export default Main;
